"""Add one-time secret fields

Revision ID: 1de199028f84
Revises: 
Create Date: 2026-08-29 15:47:01.920278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de199028f84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_time_secret_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('one_time_secret_used', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('one_time_secret_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_file', schema=None) as batch_op:
        batch_op.drop_column('one_time_secret_expires_at')
        batch_op.drop_column('one_time_secret_used')
        batch_op.drop_column('one_time_secret_hash')

    # ### end Alembic commands ###
